return {
	{
		"nvim-treesitter/nvim-treesitter",
		opts_extend = { "ensure_installed" },
		opts = {
			-- Identation was often misgaligned, especially with list items. This
			-- lets Neovim handle indentation directly. This is a bug with Treesitter
			-- and should be fixed in 1.0.
			indent = {
				disable = { "yaml" },
			},
			-- Lazy.nvim package manager will mega-merge ensure_installed
			ensure_installed = {
				"bash",
				"bitbake",
				"c",
				"comment",
				"cmake",
				"cpp",
				"csv",
				"css",
				"dart",
				"diff",
				"dockerfile",
				"git_rebase",
				"gitattributes",
				"gitcommit",
				"gitignore",
				"go",
				"gomod",
				"gosum",
				-- "html",
				"javascript",
				"json",
				"json5",
				"jsonc",
				-- "latex",
				"lua",
				"make",
				"markdown",
				"markdown_inline",
				"php",
				"python",
				"regex",
				"ruby",
				"ron",
				"rust",
				-- "tmux",
				"scss",
				"sql",
				"svelte",
				"toml",
				"tsx",
				"typescript",
				"vim",
				"vue",
				"xml",
				"yaml",
				"zig",
			},
		},
	},
}
