name: "CI"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"
      - "master"
  schedule:
    - cron: "30 12 * * *"

jobs:
  test:
    runs-on: "ubuntu-24.04"

    steps:
      - uses: "actions/checkout@v4"

      - name: "Linting and testing"
        run: |
          ./run ci:test
